http:
  routers:
    pmro-backend-http:
      rule: 'Host(`__DOMAIN__`) && PathPrefix(`/api`)'
      entryPoints:
        - web
      service: pmro-backend
      priority: 100

    pmro-frontend-http:
      rule: 'Host(`__DOMAIN__`)'
      entryPoints:
        - web
      service: pmro-frontend
      priority: 1

    pmro-backend-https:
      rule: 'Host(`__DOMAIN__`) && PathPrefix(`/api`)'
      entryPoints:
        - websecure
      service: pmro-backend
      priority: 100
      tls:
        certResolver: letsencrypt

    pmro-frontend-https:
      rule: 'Host(`__DOMAIN__`)'
      entryPoints:
        - websecure
      service: pmro-frontend
      priority: 1
      tls:
        certResolver: letsencrypt

  services:
    pmro-backend:
      loadBalancer:
        servers:
          - url: "http://backend:8000"

    pmro-frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:80"